[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/dogzilla.conf"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
